// lib/companion-catalog.ts
import type { ServiceProvider } from "./companion-types";

export const SERVICE_PROVIDER_CATALOG: ServiceProvider[] = [
  {
    id: "layanan-darurat-112",
    name: "Layanan Darurat 112",
    category: "hotline",
    description: "Nomor darurat nasional untuk situasi yang mengancam keselamatan. Bebas pulsa, 24 jam.",
    phone: "112",
    waNumber: null,
    email: null,
    website: null,
    address: "Nasional",
    operatingHours: "24 jam, 7 hari",
    isAvailable: true,
    icon: "Phone",
  },
  {
    id: "sapa-129",
    name: "SAPA 129 — KemenPPPA",
    category: "hotline",
    description: "Sahabat Perempuan dan Anak (SAPA) 129. Layanan pengaduan kekerasan terhadap perempuan dan anak oleh Kementerian PPPA.",
    phone: "129",
    waNumber: "08111129129",
    email: null,
    website: "https://sapa129.kemenpppa.go.id",
    address: "Nasional",
    operatingHours: "24 jam, 7 hari",
    isAvailable: true,
    icon: "Heart",
  },
  {
    id: "komnas-perempuan",
    name: "Komnas Perempuan",
    category: "social-service",
    description: "Komisi Nasional Anti Kekerasan terhadap Perempuan. Layanan pengaduan dan pendampingan kasus kekerasan.",
    phone: "021-3903963",
    waNumber: null,
    email: "mail@komnasperempuan.go.id",
    website: "https://komnasperempuan.go.id",
    address: "Jl. Latuharhary No. 4B, Jakarta Pusat",
    operatingHours: "Senin-Jumat, 09:00-17:00 WIB",
    isAvailable: true,
    icon: "Building2",
  },
  {
    id: "satgas-ppks-unhas",
    name: "Satgas PPKS Universitas Hasanuddin",
    category: "satgas-ppks",
    description: "Satuan Tugas Pencegahan dan Penanganan Kekerasan Seksual di lingkungan Universitas Hasanuddin.",
    phone: "081122334455",
    waNumber: "081122334455",
    email: "satgasppks@unhas.ac.id",
    website: null,
    address: "Kampus Tamalanrea, Makassar",
    operatingHours: "Senin-Jumat, 08:00-16:00 WITA",
    isAvailable: true,
    icon: "Shield",
  },
  {
    id: "lbh-makassar",
    name: "LBH Makassar",
    category: "legal-aid",
    description: "Lembaga Bantuan Hukum Makassar — pendampingan hukum gratis untuk korban kekerasan.",
    phone: "0813-5544-3322",
    waNumber: "081355443322",
    email: "lbh.makassar@gmail.com",
    website: "https://lbhmakassar.org",
    address: "Jl. Perintis Kemerdekaan No. 45, Makassar",
    operatingHours: "Senin-Jumat, 09:00-17:00 WITA",
    isAvailable: true,
    icon: "Scale",
  },
  {
    id: "pusat-psikologi-makassar",
    name: "Pusat Psikologi Terapan Makassar",
    category: "psychologist",
    description: "Layanan konseling dan terapi psikologi untuk korban kekerasan dan trauma.",
    phone: "0411-8899-7766",
    waNumber: "085299881122",
    email: "psikologi.terapan@gmail.com",
    website: null,
    address: "Jl. A.P. Pettarani No. 88, Makassar",
    operatingHours: "Senin-Sabtu, 09:00-18:00 WITA",
    isAvailable: true,
    icon: "HeartPulse",
  },
];
